// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryService.proto

package protos;

public final class InventoryServiceOuterClass {
  private InventoryServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface gInventoryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.gInventory)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Protos.gItem item = 1;</code>
     */
    boolean hasItem();
    /**
     * <code>.Protos.gItem item = 1;</code>
     */
    protos.ItemServiceOuterClass.gItem getItem();
    /**
     * <code>.Protos.gItem item = 1;</code>
     */
    protos.ItemServiceOuterClass.gItemOrBuilder getItemOrBuilder();

    /**
     * <code>.Protos.gLocation location = 2;</code>
     */
    boolean hasLocation();
    /**
     * <code>.Protos.gLocation location = 2;</code>
     */
    protos.LocationServiceOuterClass.gLocation getLocation();
    /**
     * <code>.Protos.gLocation location = 2;</code>
     */
    protos.LocationServiceOuterClass.gLocationOrBuilder getLocationOrBuilder();

    /**
     * <code>int32 id = 3;</code>
     */
    int getId();

    /**
     * <code>int32 amount = 4;</code>
     */
    int getAmount();
  }
  /**
   * Protobuf type {@code Protos.gInventory}
   */
  public  static final class gInventory extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.gInventory)
      gInventoryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use gInventory.newBuilder() to construct.
    private gInventory(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private gInventory() {
      id_ = 0;
      amount_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private gInventory(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              protos.ItemServiceOuterClass.gItem.Builder subBuilder = null;
              if (item_ != null) {
                subBuilder = item_.toBuilder();
              }
              item_ = input.readMessage(protos.ItemServiceOuterClass.gItem.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(item_);
                item_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              protos.LocationServiceOuterClass.gLocation.Builder subBuilder = null;
              if (location_ != null) {
                subBuilder = location_.toBuilder();
              }
              location_ = input.readMessage(protos.LocationServiceOuterClass.gLocation.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(location_);
                location_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              id_ = input.readInt32();
              break;
            }
            case 32: {

              amount_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.InventoryServiceOuterClass.internal_static_Protos_gInventory_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.InventoryServiceOuterClass.internal_static_Protos_gInventory_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.InventoryServiceOuterClass.gInventory.class, protos.InventoryServiceOuterClass.gInventory.Builder.class);
    }

    public static final int ITEM_FIELD_NUMBER = 1;
    private protos.ItemServiceOuterClass.gItem item_;
    /**
     * <code>.Protos.gItem item = 1;</code>
     */
    public boolean hasItem() {
      return item_ != null;
    }
    /**
     * <code>.Protos.gItem item = 1;</code>
     */
    public protos.ItemServiceOuterClass.gItem getItem() {
      return item_ == null ? protos.ItemServiceOuterClass.gItem.getDefaultInstance() : item_;
    }
    /**
     * <code>.Protos.gItem item = 1;</code>
     */
    public protos.ItemServiceOuterClass.gItemOrBuilder getItemOrBuilder() {
      return getItem();
    }

    public static final int LOCATION_FIELD_NUMBER = 2;
    private protos.LocationServiceOuterClass.gLocation location_;
    /**
     * <code>.Protos.gLocation location = 2;</code>
     */
    public boolean hasLocation() {
      return location_ != null;
    }
    /**
     * <code>.Protos.gLocation location = 2;</code>
     */
    public protos.LocationServiceOuterClass.gLocation getLocation() {
      return location_ == null ? protos.LocationServiceOuterClass.gLocation.getDefaultInstance() : location_;
    }
    /**
     * <code>.Protos.gLocation location = 2;</code>
     */
    public protos.LocationServiceOuterClass.gLocationOrBuilder getLocationOrBuilder() {
      return getLocation();
    }

    public static final int ID_FIELD_NUMBER = 3;
    private int id_;
    /**
     * <code>int32 id = 3;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int AMOUNT_FIELD_NUMBER = 4;
    private int amount_;
    /**
     * <code>int32 amount = 4;</code>
     */
    public int getAmount() {
      return amount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (item_ != null) {
        output.writeMessage(1, getItem());
      }
      if (location_ != null) {
        output.writeMessage(2, getLocation());
      }
      if (id_ != 0) {
        output.writeInt32(3, id_);
      }
      if (amount_ != 0) {
        output.writeInt32(4, amount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (item_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getItem());
      }
      if (location_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLocation());
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, id_);
      }
      if (amount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, amount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.InventoryServiceOuterClass.gInventory)) {
        return super.equals(obj);
      }
      protos.InventoryServiceOuterClass.gInventory other = (protos.InventoryServiceOuterClass.gInventory) obj;

      boolean result = true;
      result = result && (hasItem() == other.hasItem());
      if (hasItem()) {
        result = result && getItem()
            .equals(other.getItem());
      }
      result = result && (hasLocation() == other.hasLocation());
      if (hasLocation()) {
        result = result && getLocation()
            .equals(other.getLocation());
      }
      result = result && (getId()
          == other.getId());
      result = result && (getAmount()
          == other.getAmount());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasItem()) {
        hash = (37 * hash) + ITEM_FIELD_NUMBER;
        hash = (53 * hash) + getItem().hashCode();
      }
      if (hasLocation()) {
        hash = (37 * hash) + LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getLocation().hashCode();
      }
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAmount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.InventoryServiceOuterClass.gInventory parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.InventoryServiceOuterClass.gInventory parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.InventoryServiceOuterClass.gInventory parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.InventoryServiceOuterClass.gInventory parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.InventoryServiceOuterClass.gInventory parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.InventoryServiceOuterClass.gInventory parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.InventoryServiceOuterClass.gInventory parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.InventoryServiceOuterClass.gInventory parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.InventoryServiceOuterClass.gInventory parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.InventoryServiceOuterClass.gInventory parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.InventoryServiceOuterClass.gInventory parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.InventoryServiceOuterClass.gInventory parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.InventoryServiceOuterClass.gInventory prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protos.gInventory}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.gInventory)
        protos.InventoryServiceOuterClass.gInventoryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.InventoryServiceOuterClass.internal_static_Protos_gInventory_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.InventoryServiceOuterClass.internal_static_Protos_gInventory_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.InventoryServiceOuterClass.gInventory.class, protos.InventoryServiceOuterClass.gInventory.Builder.class);
      }

      // Construct using protos.InventoryServiceOuterClass.gInventory.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (itemBuilder_ == null) {
          item_ = null;
        } else {
          item_ = null;
          itemBuilder_ = null;
        }
        if (locationBuilder_ == null) {
          location_ = null;
        } else {
          location_ = null;
          locationBuilder_ = null;
        }
        id_ = 0;

        amount_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.InventoryServiceOuterClass.internal_static_Protos_gInventory_descriptor;
      }

      @java.lang.Override
      public protos.InventoryServiceOuterClass.gInventory getDefaultInstanceForType() {
        return protos.InventoryServiceOuterClass.gInventory.getDefaultInstance();
      }

      @java.lang.Override
      public protos.InventoryServiceOuterClass.gInventory build() {
        protos.InventoryServiceOuterClass.gInventory result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.InventoryServiceOuterClass.gInventory buildPartial() {
        protos.InventoryServiceOuterClass.gInventory result = new protos.InventoryServiceOuterClass.gInventory(this);
        if (itemBuilder_ == null) {
          result.item_ = item_;
        } else {
          result.item_ = itemBuilder_.build();
        }
        if (locationBuilder_ == null) {
          result.location_ = location_;
        } else {
          result.location_ = locationBuilder_.build();
        }
        result.id_ = id_;
        result.amount_ = amount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.InventoryServiceOuterClass.gInventory) {
          return mergeFrom((protos.InventoryServiceOuterClass.gInventory)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.InventoryServiceOuterClass.gInventory other) {
        if (other == protos.InventoryServiceOuterClass.gInventory.getDefaultInstance()) return this;
        if (other.hasItem()) {
          mergeItem(other.getItem());
        }
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getAmount() != 0) {
          setAmount(other.getAmount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.InventoryServiceOuterClass.gInventory parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.InventoryServiceOuterClass.gInventory) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private protos.ItemServiceOuterClass.gItem item_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          protos.ItemServiceOuterClass.gItem, protos.ItemServiceOuterClass.gItem.Builder, protos.ItemServiceOuterClass.gItemOrBuilder> itemBuilder_;
      /**
       * <code>.Protos.gItem item = 1;</code>
       */
      public boolean hasItem() {
        return itemBuilder_ != null || item_ != null;
      }
      /**
       * <code>.Protos.gItem item = 1;</code>
       */
      public protos.ItemServiceOuterClass.gItem getItem() {
        if (itemBuilder_ == null) {
          return item_ == null ? protos.ItemServiceOuterClass.gItem.getDefaultInstance() : item_;
        } else {
          return itemBuilder_.getMessage();
        }
      }
      /**
       * <code>.Protos.gItem item = 1;</code>
       */
      public Builder setItem(protos.ItemServiceOuterClass.gItem value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          item_ = value;
          onChanged();
        } else {
          itemBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Protos.gItem item = 1;</code>
       */
      public Builder setItem(
          protos.ItemServiceOuterClass.gItem.Builder builderForValue) {
        if (itemBuilder_ == null) {
          item_ = builderForValue.build();
          onChanged();
        } else {
          itemBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Protos.gItem item = 1;</code>
       */
      public Builder mergeItem(protos.ItemServiceOuterClass.gItem value) {
        if (itemBuilder_ == null) {
          if (item_ != null) {
            item_ =
              protos.ItemServiceOuterClass.gItem.newBuilder(item_).mergeFrom(value).buildPartial();
          } else {
            item_ = value;
          }
          onChanged();
        } else {
          itemBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Protos.gItem item = 1;</code>
       */
      public Builder clearItem() {
        if (itemBuilder_ == null) {
          item_ = null;
          onChanged();
        } else {
          item_ = null;
          itemBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Protos.gItem item = 1;</code>
       */
      public protos.ItemServiceOuterClass.gItem.Builder getItemBuilder() {
        
        onChanged();
        return getItemFieldBuilder().getBuilder();
      }
      /**
       * <code>.Protos.gItem item = 1;</code>
       */
      public protos.ItemServiceOuterClass.gItemOrBuilder getItemOrBuilder() {
        if (itemBuilder_ != null) {
          return itemBuilder_.getMessageOrBuilder();
        } else {
          return item_ == null ?
              protos.ItemServiceOuterClass.gItem.getDefaultInstance() : item_;
        }
      }
      /**
       * <code>.Protos.gItem item = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protos.ItemServiceOuterClass.gItem, protos.ItemServiceOuterClass.gItem.Builder, protos.ItemServiceOuterClass.gItemOrBuilder> 
          getItemFieldBuilder() {
        if (itemBuilder_ == null) {
          itemBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protos.ItemServiceOuterClass.gItem, protos.ItemServiceOuterClass.gItem.Builder, protos.ItemServiceOuterClass.gItemOrBuilder>(
                  getItem(),
                  getParentForChildren(),
                  isClean());
          item_ = null;
        }
        return itemBuilder_;
      }

      private protos.LocationServiceOuterClass.gLocation location_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          protos.LocationServiceOuterClass.gLocation, protos.LocationServiceOuterClass.gLocation.Builder, protos.LocationServiceOuterClass.gLocationOrBuilder> locationBuilder_;
      /**
       * <code>.Protos.gLocation location = 2;</code>
       */
      public boolean hasLocation() {
        return locationBuilder_ != null || location_ != null;
      }
      /**
       * <code>.Protos.gLocation location = 2;</code>
       */
      public protos.LocationServiceOuterClass.gLocation getLocation() {
        if (locationBuilder_ == null) {
          return location_ == null ? protos.LocationServiceOuterClass.gLocation.getDefaultInstance() : location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>.Protos.gLocation location = 2;</code>
       */
      public Builder setLocation(protos.LocationServiceOuterClass.gLocation value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
          onChanged();
        } else {
          locationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Protos.gLocation location = 2;</code>
       */
      public Builder setLocation(
          protos.LocationServiceOuterClass.gLocation.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
          onChanged();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Protos.gLocation location = 2;</code>
       */
      public Builder mergeLocation(protos.LocationServiceOuterClass.gLocation value) {
        if (locationBuilder_ == null) {
          if (location_ != null) {
            location_ =
              protos.LocationServiceOuterClass.gLocation.newBuilder(location_).mergeFrom(value).buildPartial();
          } else {
            location_ = value;
          }
          onChanged();
        } else {
          locationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Protos.gLocation location = 2;</code>
       */
      public Builder clearLocation() {
        if (locationBuilder_ == null) {
          location_ = null;
          onChanged();
        } else {
          location_ = null;
          locationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Protos.gLocation location = 2;</code>
       */
      public protos.LocationServiceOuterClass.gLocation.Builder getLocationBuilder() {
        
        onChanged();
        return getLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>.Protos.gLocation location = 2;</code>
       */
      public protos.LocationServiceOuterClass.gLocationOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_ == null ?
              protos.LocationServiceOuterClass.gLocation.getDefaultInstance() : location_;
        }
      }
      /**
       * <code>.Protos.gLocation location = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protos.LocationServiceOuterClass.gLocation, protos.LocationServiceOuterClass.gLocation.Builder, protos.LocationServiceOuterClass.gLocationOrBuilder> 
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protos.LocationServiceOuterClass.gLocation, protos.LocationServiceOuterClass.gLocation.Builder, protos.LocationServiceOuterClass.gLocationOrBuilder>(
                  getLocation(),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }

      private int id_ ;
      /**
       * <code>int32 id = 3;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 3;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 3;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int amount_ ;
      /**
       * <code>int32 amount = 4;</code>
       */
      public int getAmount() {
        return amount_;
      }
      /**
       * <code>int32 amount = 4;</code>
       */
      public Builder setAmount(int value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 amount = 4;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.gInventory)
    }

    // @@protoc_insertion_point(class_scope:Protos.gInventory)
    private static final protos.InventoryServiceOuterClass.gInventory DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.InventoryServiceOuterClass.gInventory();
    }

    public static protos.InventoryServiceOuterClass.gInventory getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<gInventory>
        PARSER = new com.google.protobuf.AbstractParser<gInventory>() {
      @java.lang.Override
      public gInventory parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new gInventory(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<gInventory> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<gInventory> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.InventoryServiceOuterClass.gInventory getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface gInventoryListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.gInventoryList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Protos.gInventory Inventorys = 1;</code>
     */
    java.util.List<protos.InventoryServiceOuterClass.gInventory> 
        getInventorysList();
    /**
     * <code>repeated .Protos.gInventory Inventorys = 1;</code>
     */
    protos.InventoryServiceOuterClass.gInventory getInventorys(int index);
    /**
     * <code>repeated .Protos.gInventory Inventorys = 1;</code>
     */
    int getInventorysCount();
    /**
     * <code>repeated .Protos.gInventory Inventorys = 1;</code>
     */
    java.util.List<? extends protos.InventoryServiceOuterClass.gInventoryOrBuilder> 
        getInventorysOrBuilderList();
    /**
     * <code>repeated .Protos.gInventory Inventorys = 1;</code>
     */
    protos.InventoryServiceOuterClass.gInventoryOrBuilder getInventorysOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Protos.gInventoryList}
   */
  public  static final class gInventoryList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.gInventoryList)
      gInventoryListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use gInventoryList.newBuilder() to construct.
    private gInventoryList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private gInventoryList() {
      inventorys_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private gInventoryList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                inventorys_ = new java.util.ArrayList<protos.InventoryServiceOuterClass.gInventory>();
                mutable_bitField0_ |= 0x00000001;
              }
              inventorys_.add(
                  input.readMessage(protos.InventoryServiceOuterClass.gInventory.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          inventorys_ = java.util.Collections.unmodifiableList(inventorys_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.InventoryServiceOuterClass.internal_static_Protos_gInventoryList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.InventoryServiceOuterClass.internal_static_Protos_gInventoryList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.InventoryServiceOuterClass.gInventoryList.class, protos.InventoryServiceOuterClass.gInventoryList.Builder.class);
    }

    public static final int INVENTORYS_FIELD_NUMBER = 1;
    private java.util.List<protos.InventoryServiceOuterClass.gInventory> inventorys_;
    /**
     * <code>repeated .Protos.gInventory Inventorys = 1;</code>
     */
    public java.util.List<protos.InventoryServiceOuterClass.gInventory> getInventorysList() {
      return inventorys_;
    }
    /**
     * <code>repeated .Protos.gInventory Inventorys = 1;</code>
     */
    public java.util.List<? extends protos.InventoryServiceOuterClass.gInventoryOrBuilder> 
        getInventorysOrBuilderList() {
      return inventorys_;
    }
    /**
     * <code>repeated .Protos.gInventory Inventorys = 1;</code>
     */
    public int getInventorysCount() {
      return inventorys_.size();
    }
    /**
     * <code>repeated .Protos.gInventory Inventorys = 1;</code>
     */
    public protos.InventoryServiceOuterClass.gInventory getInventorys(int index) {
      return inventorys_.get(index);
    }
    /**
     * <code>repeated .Protos.gInventory Inventorys = 1;</code>
     */
    public protos.InventoryServiceOuterClass.gInventoryOrBuilder getInventorysOrBuilder(
        int index) {
      return inventorys_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < inventorys_.size(); i++) {
        output.writeMessage(1, inventorys_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < inventorys_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, inventorys_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.InventoryServiceOuterClass.gInventoryList)) {
        return super.equals(obj);
      }
      protos.InventoryServiceOuterClass.gInventoryList other = (protos.InventoryServiceOuterClass.gInventoryList) obj;

      boolean result = true;
      result = result && getInventorysList()
          .equals(other.getInventorysList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getInventorysCount() > 0) {
        hash = (37 * hash) + INVENTORYS_FIELD_NUMBER;
        hash = (53 * hash) + getInventorysList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.InventoryServiceOuterClass.gInventoryList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.InventoryServiceOuterClass.gInventoryList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.InventoryServiceOuterClass.gInventoryList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.InventoryServiceOuterClass.gInventoryList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.InventoryServiceOuterClass.gInventoryList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.InventoryServiceOuterClass.gInventoryList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.InventoryServiceOuterClass.gInventoryList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.InventoryServiceOuterClass.gInventoryList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.InventoryServiceOuterClass.gInventoryList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.InventoryServiceOuterClass.gInventoryList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.InventoryServiceOuterClass.gInventoryList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.InventoryServiceOuterClass.gInventoryList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.InventoryServiceOuterClass.gInventoryList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protos.gInventoryList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.gInventoryList)
        protos.InventoryServiceOuterClass.gInventoryListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.InventoryServiceOuterClass.internal_static_Protos_gInventoryList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.InventoryServiceOuterClass.internal_static_Protos_gInventoryList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.InventoryServiceOuterClass.gInventoryList.class, protos.InventoryServiceOuterClass.gInventoryList.Builder.class);
      }

      // Construct using protos.InventoryServiceOuterClass.gInventoryList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInventorysFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (inventorysBuilder_ == null) {
          inventorys_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          inventorysBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.InventoryServiceOuterClass.internal_static_Protos_gInventoryList_descriptor;
      }

      @java.lang.Override
      public protos.InventoryServiceOuterClass.gInventoryList getDefaultInstanceForType() {
        return protos.InventoryServiceOuterClass.gInventoryList.getDefaultInstance();
      }

      @java.lang.Override
      public protos.InventoryServiceOuterClass.gInventoryList build() {
        protos.InventoryServiceOuterClass.gInventoryList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.InventoryServiceOuterClass.gInventoryList buildPartial() {
        protos.InventoryServiceOuterClass.gInventoryList result = new protos.InventoryServiceOuterClass.gInventoryList(this);
        int from_bitField0_ = bitField0_;
        if (inventorysBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            inventorys_ = java.util.Collections.unmodifiableList(inventorys_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.inventorys_ = inventorys_;
        } else {
          result.inventorys_ = inventorysBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.InventoryServiceOuterClass.gInventoryList) {
          return mergeFrom((protos.InventoryServiceOuterClass.gInventoryList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.InventoryServiceOuterClass.gInventoryList other) {
        if (other == protos.InventoryServiceOuterClass.gInventoryList.getDefaultInstance()) return this;
        if (inventorysBuilder_ == null) {
          if (!other.inventorys_.isEmpty()) {
            if (inventorys_.isEmpty()) {
              inventorys_ = other.inventorys_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureInventorysIsMutable();
              inventorys_.addAll(other.inventorys_);
            }
            onChanged();
          }
        } else {
          if (!other.inventorys_.isEmpty()) {
            if (inventorysBuilder_.isEmpty()) {
              inventorysBuilder_.dispose();
              inventorysBuilder_ = null;
              inventorys_ = other.inventorys_;
              bitField0_ = (bitField0_ & ~0x00000001);
              inventorysBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getInventorysFieldBuilder() : null;
            } else {
              inventorysBuilder_.addAllMessages(other.inventorys_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.InventoryServiceOuterClass.gInventoryList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.InventoryServiceOuterClass.gInventoryList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<protos.InventoryServiceOuterClass.gInventory> inventorys_ =
        java.util.Collections.emptyList();
      private void ensureInventorysIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          inventorys_ = new java.util.ArrayList<protos.InventoryServiceOuterClass.gInventory>(inventorys_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protos.InventoryServiceOuterClass.gInventory, protos.InventoryServiceOuterClass.gInventory.Builder, protos.InventoryServiceOuterClass.gInventoryOrBuilder> inventorysBuilder_;

      /**
       * <code>repeated .Protos.gInventory Inventorys = 1;</code>
       */
      public java.util.List<protos.InventoryServiceOuterClass.gInventory> getInventorysList() {
        if (inventorysBuilder_ == null) {
          return java.util.Collections.unmodifiableList(inventorys_);
        } else {
          return inventorysBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Protos.gInventory Inventorys = 1;</code>
       */
      public int getInventorysCount() {
        if (inventorysBuilder_ == null) {
          return inventorys_.size();
        } else {
          return inventorysBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Protos.gInventory Inventorys = 1;</code>
       */
      public protos.InventoryServiceOuterClass.gInventory getInventorys(int index) {
        if (inventorysBuilder_ == null) {
          return inventorys_.get(index);
        } else {
          return inventorysBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Protos.gInventory Inventorys = 1;</code>
       */
      public Builder setInventorys(
          int index, protos.InventoryServiceOuterClass.gInventory value) {
        if (inventorysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInventorysIsMutable();
          inventorys_.set(index, value);
          onChanged();
        } else {
          inventorysBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gInventory Inventorys = 1;</code>
       */
      public Builder setInventorys(
          int index, protos.InventoryServiceOuterClass.gInventory.Builder builderForValue) {
        if (inventorysBuilder_ == null) {
          ensureInventorysIsMutable();
          inventorys_.set(index, builderForValue.build());
          onChanged();
        } else {
          inventorysBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gInventory Inventorys = 1;</code>
       */
      public Builder addInventorys(protos.InventoryServiceOuterClass.gInventory value) {
        if (inventorysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInventorysIsMutable();
          inventorys_.add(value);
          onChanged();
        } else {
          inventorysBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gInventory Inventorys = 1;</code>
       */
      public Builder addInventorys(
          int index, protos.InventoryServiceOuterClass.gInventory value) {
        if (inventorysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInventorysIsMutable();
          inventorys_.add(index, value);
          onChanged();
        } else {
          inventorysBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gInventory Inventorys = 1;</code>
       */
      public Builder addInventorys(
          protos.InventoryServiceOuterClass.gInventory.Builder builderForValue) {
        if (inventorysBuilder_ == null) {
          ensureInventorysIsMutable();
          inventorys_.add(builderForValue.build());
          onChanged();
        } else {
          inventorysBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gInventory Inventorys = 1;</code>
       */
      public Builder addInventorys(
          int index, protos.InventoryServiceOuterClass.gInventory.Builder builderForValue) {
        if (inventorysBuilder_ == null) {
          ensureInventorysIsMutable();
          inventorys_.add(index, builderForValue.build());
          onChanged();
        } else {
          inventorysBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gInventory Inventorys = 1;</code>
       */
      public Builder addAllInventorys(
          java.lang.Iterable<? extends protos.InventoryServiceOuterClass.gInventory> values) {
        if (inventorysBuilder_ == null) {
          ensureInventorysIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, inventorys_);
          onChanged();
        } else {
          inventorysBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gInventory Inventorys = 1;</code>
       */
      public Builder clearInventorys() {
        if (inventorysBuilder_ == null) {
          inventorys_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          inventorysBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gInventory Inventorys = 1;</code>
       */
      public Builder removeInventorys(int index) {
        if (inventorysBuilder_ == null) {
          ensureInventorysIsMutable();
          inventorys_.remove(index);
          onChanged();
        } else {
          inventorysBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gInventory Inventorys = 1;</code>
       */
      public protos.InventoryServiceOuterClass.gInventory.Builder getInventorysBuilder(
          int index) {
        return getInventorysFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Protos.gInventory Inventorys = 1;</code>
       */
      public protos.InventoryServiceOuterClass.gInventoryOrBuilder getInventorysOrBuilder(
          int index) {
        if (inventorysBuilder_ == null) {
          return inventorys_.get(index);  } else {
          return inventorysBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Protos.gInventory Inventorys = 1;</code>
       */
      public java.util.List<? extends protos.InventoryServiceOuterClass.gInventoryOrBuilder> 
           getInventorysOrBuilderList() {
        if (inventorysBuilder_ != null) {
          return inventorysBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(inventorys_);
        }
      }
      /**
       * <code>repeated .Protos.gInventory Inventorys = 1;</code>
       */
      public protos.InventoryServiceOuterClass.gInventory.Builder addInventorysBuilder() {
        return getInventorysFieldBuilder().addBuilder(
            protos.InventoryServiceOuterClass.gInventory.getDefaultInstance());
      }
      /**
       * <code>repeated .Protos.gInventory Inventorys = 1;</code>
       */
      public protos.InventoryServiceOuterClass.gInventory.Builder addInventorysBuilder(
          int index) {
        return getInventorysFieldBuilder().addBuilder(
            index, protos.InventoryServiceOuterClass.gInventory.getDefaultInstance());
      }
      /**
       * <code>repeated .Protos.gInventory Inventorys = 1;</code>
       */
      public java.util.List<protos.InventoryServiceOuterClass.gInventory.Builder> 
           getInventorysBuilderList() {
        return getInventorysFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protos.InventoryServiceOuterClass.gInventory, protos.InventoryServiceOuterClass.gInventory.Builder, protos.InventoryServiceOuterClass.gInventoryOrBuilder> 
          getInventorysFieldBuilder() {
        if (inventorysBuilder_ == null) {
          inventorysBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protos.InventoryServiceOuterClass.gInventory, protos.InventoryServiceOuterClass.gInventory.Builder, protos.InventoryServiceOuterClass.gInventoryOrBuilder>(
                  inventorys_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          inventorys_ = null;
        }
        return inventorysBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.gInventoryList)
    }

    // @@protoc_insertion_point(class_scope:Protos.gInventoryList)
    private static final protos.InventoryServiceOuterClass.gInventoryList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.InventoryServiceOuterClass.gInventoryList();
    }

    public static protos.InventoryServiceOuterClass.gInventoryList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<gInventoryList>
        PARSER = new com.google.protobuf.AbstractParser<gInventoryList>() {
      @java.lang.Override
      public gInventoryList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new gInventoryList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<gInventoryList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<gInventoryList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.InventoryServiceOuterClass.gInventoryList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface gInventoryIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.gInventoryId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 InventoryId = 1;</code>
     */
    int getInventoryId();
  }
  /**
   * Protobuf type {@code Protos.gInventoryId}
   */
  public  static final class gInventoryId extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.gInventoryId)
      gInventoryIdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use gInventoryId.newBuilder() to construct.
    private gInventoryId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private gInventoryId() {
      inventoryId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private gInventoryId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              inventoryId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.InventoryServiceOuterClass.internal_static_Protos_gInventoryId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.InventoryServiceOuterClass.internal_static_Protos_gInventoryId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.InventoryServiceOuterClass.gInventoryId.class, protos.InventoryServiceOuterClass.gInventoryId.Builder.class);
    }

    public static final int INVENTORYID_FIELD_NUMBER = 1;
    private int inventoryId_;
    /**
     * <code>int32 InventoryId = 1;</code>
     */
    public int getInventoryId() {
      return inventoryId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (inventoryId_ != 0) {
        output.writeInt32(1, inventoryId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (inventoryId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, inventoryId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.InventoryServiceOuterClass.gInventoryId)) {
        return super.equals(obj);
      }
      protos.InventoryServiceOuterClass.gInventoryId other = (protos.InventoryServiceOuterClass.gInventoryId) obj;

      boolean result = true;
      result = result && (getInventoryId()
          == other.getInventoryId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INVENTORYID_FIELD_NUMBER;
      hash = (53 * hash) + getInventoryId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.InventoryServiceOuterClass.gInventoryId parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.InventoryServiceOuterClass.gInventoryId parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.InventoryServiceOuterClass.gInventoryId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.InventoryServiceOuterClass.gInventoryId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.InventoryServiceOuterClass.gInventoryId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.InventoryServiceOuterClass.gInventoryId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.InventoryServiceOuterClass.gInventoryId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.InventoryServiceOuterClass.gInventoryId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.InventoryServiceOuterClass.gInventoryId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.InventoryServiceOuterClass.gInventoryId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.InventoryServiceOuterClass.gInventoryId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.InventoryServiceOuterClass.gInventoryId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.InventoryServiceOuterClass.gInventoryId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protos.gInventoryId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.gInventoryId)
        protos.InventoryServiceOuterClass.gInventoryIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.InventoryServiceOuterClass.internal_static_Protos_gInventoryId_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.InventoryServiceOuterClass.internal_static_Protos_gInventoryId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.InventoryServiceOuterClass.gInventoryId.class, protos.InventoryServiceOuterClass.gInventoryId.Builder.class);
      }

      // Construct using protos.InventoryServiceOuterClass.gInventoryId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        inventoryId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.InventoryServiceOuterClass.internal_static_Protos_gInventoryId_descriptor;
      }

      @java.lang.Override
      public protos.InventoryServiceOuterClass.gInventoryId getDefaultInstanceForType() {
        return protos.InventoryServiceOuterClass.gInventoryId.getDefaultInstance();
      }

      @java.lang.Override
      public protos.InventoryServiceOuterClass.gInventoryId build() {
        protos.InventoryServiceOuterClass.gInventoryId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.InventoryServiceOuterClass.gInventoryId buildPartial() {
        protos.InventoryServiceOuterClass.gInventoryId result = new protos.InventoryServiceOuterClass.gInventoryId(this);
        result.inventoryId_ = inventoryId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.InventoryServiceOuterClass.gInventoryId) {
          return mergeFrom((protos.InventoryServiceOuterClass.gInventoryId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.InventoryServiceOuterClass.gInventoryId other) {
        if (other == protos.InventoryServiceOuterClass.gInventoryId.getDefaultInstance()) return this;
        if (other.getInventoryId() != 0) {
          setInventoryId(other.getInventoryId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.InventoryServiceOuterClass.gInventoryId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.InventoryServiceOuterClass.gInventoryId) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int inventoryId_ ;
      /**
       * <code>int32 InventoryId = 1;</code>
       */
      public int getInventoryId() {
        return inventoryId_;
      }
      /**
       * <code>int32 InventoryId = 1;</code>
       */
      public Builder setInventoryId(int value) {
        
        inventoryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 InventoryId = 1;</code>
       */
      public Builder clearInventoryId() {
        
        inventoryId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.gInventoryId)
    }

    // @@protoc_insertion_point(class_scope:Protos.gInventoryId)
    private static final protos.InventoryServiceOuterClass.gInventoryId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.InventoryServiceOuterClass.gInventoryId();
    }

    public static protos.InventoryServiceOuterClass.gInventoryId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<gInventoryId>
        PARSER = new com.google.protobuf.AbstractParser<gInventoryId>() {
      @java.lang.Override
      public gInventoryId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new gInventoryId(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<gInventoryId> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<gInventoryId> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.InventoryServiceOuterClass.gInventoryId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_gInventory_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_gInventory_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_gInventoryList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_gInventoryList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_gInventoryId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_gInventoryId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026InventoryService.proto\022\006Protos\032\021ItemSe" +
      "rvice.proto\032\025LocationService.proto\032\017Prot" +
      "oUtil.proto\"j\n\ngInventory\022\033\n\004item\030\001 \001(\0132" +
      "\r.Protos.gItem\022#\n\010location\030\002 \001(\0132\021.Proto" +
      "s.gLocation\022\n\n\002id\030\003 \001(\005\022\016\n\006amount\030\004 \001(\005\"" +
      "8\n\016gInventoryList\022&\n\nInventorys\030\001 \003(\0132\022." +
      "Protos.gInventory\"#\n\014gInventoryId\022\023\n\013Inv" +
      "entoryId\030\001 \001(\0052\271\003\n\020InventoryService\022;\n\021R" +
      "egisterInventory\022\022.Protos.gInventory\032\022.P" +
      "rotos.gInventory\0228\n\014GetInventory\022\024.Proto" +
      "s.gInventoryId\032\022.Protos.gInventory\022>\n\020Ge" +
      "tAllInventorys\022\022.Protos.gInventory\032\026.Pro" +
      "tos.gInventoryList\0229\n\017UpdateInventory\022\022." +
      "Protos.gInventory\032\022.Protos.gInventory\022;\n" +
      "\017RemoveInventory\022\024.Protos.gInventoryId\032\022" +
      ".Protos.gBoolValue\0226\n\013GetByItemId\022\017.Prot" +
      "os.gItemId\032\026.Protos.gInventoryList\022>\n\017Ge" +
      "tByLocationId\022\023.Protos.gLocationId\032\026.Pro" +
      "tos.gInventoryListB\021\n\006protos\252\002\006myGrpcb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protos.ItemServiceOuterClass.getDescriptor(),
          protos.LocationServiceOuterClass.getDescriptor(),
          Protos.ProtoUtil.getDescriptor(),
        }, assigner);
    internal_static_Protos_gInventory_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Protos_gInventory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_gInventory_descriptor,
        new java.lang.String[] { "Item", "Location", "Id", "Amount", });
    internal_static_Protos_gInventoryList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Protos_gInventoryList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_gInventoryList_descriptor,
        new java.lang.String[] { "Inventorys", });
    internal_static_Protos_gInventoryId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Protos_gInventoryId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_gInventoryId_descriptor,
        new java.lang.String[] { "InventoryId", });
    protos.ItemServiceOuterClass.getDescriptor();
    protos.LocationServiceOuterClass.getDescriptor();
    Protos.ProtoUtil.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
