// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemService.proto

package protos;

public final class ItemServiceOuterClass {
  private ItemServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface gItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.gItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 Id = 1;</code>
     */
    int getId();

    /**
     * <code>string itemName = 2;</code>
     */
    java.lang.String getItemName();
    /**
     * <code>string itemName = 2;</code>
     */
    com.google.protobuf.ByteString
        getItemNameBytes();

    /**
     * <code>double length = 3;</code>
     */
    double getLength();

    /**
     * <code>double width = 4;</code>
     */
    double getWidth();

    /**
     * <code>double height = 5;</code>
     */
    double getHeight();

    /**
     * <code>double weight = 6;</code>
     */
    double getWeight();
  }
  /**
   * Protobuf type {@code Protos.gItem}
   */
  public  static final class gItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.gItem)
      gItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use gItem.newBuilder() to construct.
    private gItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private gItem() {
      id_ = 0;
      itemName_ = "";
      length_ = 0D;
      width_ = 0D;
      height_ = 0D;
      weight_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private gItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              itemName_ = s;
              break;
            }
            case 25: {

              length_ = input.readDouble();
              break;
            }
            case 33: {

              width_ = input.readDouble();
              break;
            }
            case 41: {

              height_ = input.readDouble();
              break;
            }
            case 49: {

              weight_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.ItemServiceOuterClass.internal_static_Protos_gItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.ItemServiceOuterClass.internal_static_Protos_gItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.ItemServiceOuterClass.gItem.class, protos.ItemServiceOuterClass.gItem.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 Id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int ITEMNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object itemName_;
    /**
     * <code>string itemName = 2;</code>
     */
    public java.lang.String getItemName() {
      java.lang.Object ref = itemName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        itemName_ = s;
        return s;
      }
    }
    /**
     * <code>string itemName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getItemNameBytes() {
      java.lang.Object ref = itemName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LENGTH_FIELD_NUMBER = 3;
    private double length_;
    /**
     * <code>double length = 3;</code>
     */
    public double getLength() {
      return length_;
    }

    public static final int WIDTH_FIELD_NUMBER = 4;
    private double width_;
    /**
     * <code>double width = 4;</code>
     */
    public double getWidth() {
      return width_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 5;
    private double height_;
    /**
     * <code>double height = 5;</code>
     */
    public double getHeight() {
      return height_;
    }

    public static final int WEIGHT_FIELD_NUMBER = 6;
    private double weight_;
    /**
     * <code>double weight = 6;</code>
     */
    public double getWeight() {
      return weight_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getItemNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, itemName_);
      }
      if (length_ != 0D) {
        output.writeDouble(3, length_);
      }
      if (width_ != 0D) {
        output.writeDouble(4, width_);
      }
      if (height_ != 0D) {
        output.writeDouble(5, height_);
      }
      if (weight_ != 0D) {
        output.writeDouble(6, weight_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getItemNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, itemName_);
      }
      if (length_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, length_);
      }
      if (width_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, width_);
      }
      if (height_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, height_);
      }
      if (weight_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, weight_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.ItemServiceOuterClass.gItem)) {
        return super.equals(obj);
      }
      protos.ItemServiceOuterClass.gItem other = (protos.ItemServiceOuterClass.gItem) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getItemName()
          .equals(other.getItemName());
      result = result && (
          java.lang.Double.doubleToLongBits(getLength())
          == java.lang.Double.doubleToLongBits(
              other.getLength()));
      result = result && (
          java.lang.Double.doubleToLongBits(getWidth())
          == java.lang.Double.doubleToLongBits(
              other.getWidth()));
      result = result && (
          java.lang.Double.doubleToLongBits(getHeight())
          == java.lang.Double.doubleToLongBits(
              other.getHeight()));
      result = result && (
          java.lang.Double.doubleToLongBits(getWeight())
          == java.lang.Double.doubleToLongBits(
              other.getWeight()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + ITEMNAME_FIELD_NUMBER;
      hash = (53 * hash) + getItemName().hashCode();
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLength()));
      hash = (37 * hash) + WIDTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getWidth()));
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getHeight()));
      hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getWeight()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.ItemServiceOuterClass.gItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.ItemServiceOuterClass.gItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.ItemServiceOuterClass.gItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.ItemServiceOuterClass.gItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.ItemServiceOuterClass.gItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.ItemServiceOuterClass.gItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.ItemServiceOuterClass.gItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.ItemServiceOuterClass.gItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.ItemServiceOuterClass.gItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.ItemServiceOuterClass.gItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.ItemServiceOuterClass.gItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.ItemServiceOuterClass.gItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.ItemServiceOuterClass.gItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protos.gItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.gItem)
        protos.ItemServiceOuterClass.gItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.ItemServiceOuterClass.internal_static_Protos_gItem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.ItemServiceOuterClass.internal_static_Protos_gItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.ItemServiceOuterClass.gItem.class, protos.ItemServiceOuterClass.gItem.Builder.class);
      }

      // Construct using protos.ItemServiceOuterClass.gItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        itemName_ = "";

        length_ = 0D;

        width_ = 0D;

        height_ = 0D;

        weight_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.ItemServiceOuterClass.internal_static_Protos_gItem_descriptor;
      }

      @java.lang.Override
      public protos.ItemServiceOuterClass.gItem getDefaultInstanceForType() {
        return protos.ItemServiceOuterClass.gItem.getDefaultInstance();
      }

      @java.lang.Override
      public protos.ItemServiceOuterClass.gItem build() {
        protos.ItemServiceOuterClass.gItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.ItemServiceOuterClass.gItem buildPartial() {
        protos.ItemServiceOuterClass.gItem result = new protos.ItemServiceOuterClass.gItem(this);
        result.id_ = id_;
        result.itemName_ = itemName_;
        result.length_ = length_;
        result.width_ = width_;
        result.height_ = height_;
        result.weight_ = weight_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.ItemServiceOuterClass.gItem) {
          return mergeFrom((protos.ItemServiceOuterClass.gItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.ItemServiceOuterClass.gItem other) {
        if (other == protos.ItemServiceOuterClass.gItem.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getItemName().isEmpty()) {
          itemName_ = other.itemName_;
          onChanged();
        }
        if (other.getLength() != 0D) {
          setLength(other.getLength());
        }
        if (other.getWidth() != 0D) {
          setWidth(other.getWidth());
        }
        if (other.getHeight() != 0D) {
          setHeight(other.getHeight());
        }
        if (other.getWeight() != 0D) {
          setWeight(other.getWeight());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.ItemServiceOuterClass.gItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.ItemServiceOuterClass.gItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 Id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 Id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object itemName_ = "";
      /**
       * <code>string itemName = 2;</code>
       */
      public java.lang.String getItemName() {
        java.lang.Object ref = itemName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          itemName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string itemName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getItemNameBytes() {
        java.lang.Object ref = itemName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          itemName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string itemName = 2;</code>
       */
      public Builder setItemName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        itemName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string itemName = 2;</code>
       */
      public Builder clearItemName() {
        
        itemName_ = getDefaultInstance().getItemName();
        onChanged();
        return this;
      }
      /**
       * <code>string itemName = 2;</code>
       */
      public Builder setItemNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        itemName_ = value;
        onChanged();
        return this;
      }

      private double length_ ;
      /**
       * <code>double length = 3;</code>
       */
      public double getLength() {
        return length_;
      }
      /**
       * <code>double length = 3;</code>
       */
      public Builder setLength(double value) {
        
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double length = 3;</code>
       */
      public Builder clearLength() {
        
        length_ = 0D;
        onChanged();
        return this;
      }

      private double width_ ;
      /**
       * <code>double width = 4;</code>
       */
      public double getWidth() {
        return width_;
      }
      /**
       * <code>double width = 4;</code>
       */
      public Builder setWidth(double value) {
        
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double width = 4;</code>
       */
      public Builder clearWidth() {
        
        width_ = 0D;
        onChanged();
        return this;
      }

      private double height_ ;
      /**
       * <code>double height = 5;</code>
       */
      public double getHeight() {
        return height_;
      }
      /**
       * <code>double height = 5;</code>
       */
      public Builder setHeight(double value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double height = 5;</code>
       */
      public Builder clearHeight() {
        
        height_ = 0D;
        onChanged();
        return this;
      }

      private double weight_ ;
      /**
       * <code>double weight = 6;</code>
       */
      public double getWeight() {
        return weight_;
      }
      /**
       * <code>double weight = 6;</code>
       */
      public Builder setWeight(double value) {
        
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double weight = 6;</code>
       */
      public Builder clearWeight() {
        
        weight_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.gItem)
    }

    // @@protoc_insertion_point(class_scope:Protos.gItem)
    private static final protos.ItemServiceOuterClass.gItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.ItemServiceOuterClass.gItem();
    }

    public static protos.ItemServiceOuterClass.gItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<gItem>
        PARSER = new com.google.protobuf.AbstractParser<gItem>() {
      @java.lang.Override
      public gItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new gItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<gItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<gItem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.ItemServiceOuterClass.gItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface gItemListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.gItemList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Protos.gItem item = 1;</code>
     */
    java.util.List<protos.ItemServiceOuterClass.gItem> 
        getItemList();
    /**
     * <code>repeated .Protos.gItem item = 1;</code>
     */
    protos.ItemServiceOuterClass.gItem getItem(int index);
    /**
     * <code>repeated .Protos.gItem item = 1;</code>
     */
    int getItemCount();
    /**
     * <code>repeated .Protos.gItem item = 1;</code>
     */
    java.util.List<? extends protos.ItemServiceOuterClass.gItemOrBuilder> 
        getItemOrBuilderList();
    /**
     * <code>repeated .Protos.gItem item = 1;</code>
     */
    protos.ItemServiceOuterClass.gItemOrBuilder getItemOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Protos.gItemList}
   */
  public  static final class gItemList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.gItemList)
      gItemListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use gItemList.newBuilder() to construct.
    private gItemList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private gItemList() {
      item_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private gItemList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                item_ = new java.util.ArrayList<protos.ItemServiceOuterClass.gItem>();
                mutable_bitField0_ |= 0x00000001;
              }
              item_.add(
                  input.readMessage(protos.ItemServiceOuterClass.gItem.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          item_ = java.util.Collections.unmodifiableList(item_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.ItemServiceOuterClass.internal_static_Protos_gItemList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.ItemServiceOuterClass.internal_static_Protos_gItemList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.ItemServiceOuterClass.gItemList.class, protos.ItemServiceOuterClass.gItemList.Builder.class);
    }

    public static final int ITEM_FIELD_NUMBER = 1;
    private java.util.List<protos.ItemServiceOuterClass.gItem> item_;
    /**
     * <code>repeated .Protos.gItem item = 1;</code>
     */
    public java.util.List<protos.ItemServiceOuterClass.gItem> getItemList() {
      return item_;
    }
    /**
     * <code>repeated .Protos.gItem item = 1;</code>
     */
    public java.util.List<? extends protos.ItemServiceOuterClass.gItemOrBuilder> 
        getItemOrBuilderList() {
      return item_;
    }
    /**
     * <code>repeated .Protos.gItem item = 1;</code>
     */
    public int getItemCount() {
      return item_.size();
    }
    /**
     * <code>repeated .Protos.gItem item = 1;</code>
     */
    public protos.ItemServiceOuterClass.gItem getItem(int index) {
      return item_.get(index);
    }
    /**
     * <code>repeated .Protos.gItem item = 1;</code>
     */
    public protos.ItemServiceOuterClass.gItemOrBuilder getItemOrBuilder(
        int index) {
      return item_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < item_.size(); i++) {
        output.writeMessage(1, item_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < item_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, item_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.ItemServiceOuterClass.gItemList)) {
        return super.equals(obj);
      }
      protos.ItemServiceOuterClass.gItemList other = (protos.ItemServiceOuterClass.gItemList) obj;

      boolean result = true;
      result = result && getItemList()
          .equals(other.getItemList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemCount() > 0) {
        hash = (37 * hash) + ITEM_FIELD_NUMBER;
        hash = (53 * hash) + getItemList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.ItemServiceOuterClass.gItemList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.ItemServiceOuterClass.gItemList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.ItemServiceOuterClass.gItemList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.ItemServiceOuterClass.gItemList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.ItemServiceOuterClass.gItemList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.ItemServiceOuterClass.gItemList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.ItemServiceOuterClass.gItemList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.ItemServiceOuterClass.gItemList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.ItemServiceOuterClass.gItemList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.ItemServiceOuterClass.gItemList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.ItemServiceOuterClass.gItemList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.ItemServiceOuterClass.gItemList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.ItemServiceOuterClass.gItemList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protos.gItemList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.gItemList)
        protos.ItemServiceOuterClass.gItemListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.ItemServiceOuterClass.internal_static_Protos_gItemList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.ItemServiceOuterClass.internal_static_Protos_gItemList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.ItemServiceOuterClass.gItemList.class, protos.ItemServiceOuterClass.gItemList.Builder.class);
      }

      // Construct using protos.ItemServiceOuterClass.gItemList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.ItemServiceOuterClass.internal_static_Protos_gItemList_descriptor;
      }

      @java.lang.Override
      public protos.ItemServiceOuterClass.gItemList getDefaultInstanceForType() {
        return protos.ItemServiceOuterClass.gItemList.getDefaultInstance();
      }

      @java.lang.Override
      public protos.ItemServiceOuterClass.gItemList build() {
        protos.ItemServiceOuterClass.gItemList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.ItemServiceOuterClass.gItemList buildPartial() {
        protos.ItemServiceOuterClass.gItemList result = new protos.ItemServiceOuterClass.gItemList(this);
        int from_bitField0_ = bitField0_;
        if (itemBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            item_ = java.util.Collections.unmodifiableList(item_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.item_ = item_;
        } else {
          result.item_ = itemBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.ItemServiceOuterClass.gItemList) {
          return mergeFrom((protos.ItemServiceOuterClass.gItemList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.ItemServiceOuterClass.gItemList other) {
        if (other == protos.ItemServiceOuterClass.gItemList.getDefaultInstance()) return this;
        if (itemBuilder_ == null) {
          if (!other.item_.isEmpty()) {
            if (item_.isEmpty()) {
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemIsMutable();
              item_.addAll(other.item_);
            }
            onChanged();
          }
        } else {
          if (!other.item_.isEmpty()) {
            if (itemBuilder_.isEmpty()) {
              itemBuilder_.dispose();
              itemBuilder_ = null;
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemFieldBuilder() : null;
            } else {
              itemBuilder_.addAllMessages(other.item_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.ItemServiceOuterClass.gItemList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.ItemServiceOuterClass.gItemList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<protos.ItemServiceOuterClass.gItem> item_ =
        java.util.Collections.emptyList();
      private void ensureItemIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          item_ = new java.util.ArrayList<protos.ItemServiceOuterClass.gItem>(item_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protos.ItemServiceOuterClass.gItem, protos.ItemServiceOuterClass.gItem.Builder, protos.ItemServiceOuterClass.gItemOrBuilder> itemBuilder_;

      /**
       * <code>repeated .Protos.gItem item = 1;</code>
       */
      public java.util.List<protos.ItemServiceOuterClass.gItem> getItemList() {
        if (itemBuilder_ == null) {
          return java.util.Collections.unmodifiableList(item_);
        } else {
          return itemBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Protos.gItem item = 1;</code>
       */
      public int getItemCount() {
        if (itemBuilder_ == null) {
          return item_.size();
        } else {
          return itemBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Protos.gItem item = 1;</code>
       */
      public protos.ItemServiceOuterClass.gItem getItem(int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);
        } else {
          return itemBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Protos.gItem item = 1;</code>
       */
      public Builder setItem(
          int index, protos.ItemServiceOuterClass.gItem value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.set(index, value);
          onChanged();
        } else {
          itemBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gItem item = 1;</code>
       */
      public Builder setItem(
          int index, protos.ItemServiceOuterClass.gItem.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gItem item = 1;</code>
       */
      public Builder addItem(protos.ItemServiceOuterClass.gItem value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(value);
          onChanged();
        } else {
          itemBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gItem item = 1;</code>
       */
      public Builder addItem(
          int index, protos.ItemServiceOuterClass.gItem value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(index, value);
          onChanged();
        } else {
          itemBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gItem item = 1;</code>
       */
      public Builder addItem(
          protos.ItemServiceOuterClass.gItem.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gItem item = 1;</code>
       */
      public Builder addItem(
          int index, protos.ItemServiceOuterClass.gItem.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gItem item = 1;</code>
       */
      public Builder addAllItem(
          java.lang.Iterable<? extends protos.ItemServiceOuterClass.gItem> values) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, item_);
          onChanged();
        } else {
          itemBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gItem item = 1;</code>
       */
      public Builder clearItem() {
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gItem item = 1;</code>
       */
      public Builder removeItem(int index) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.remove(index);
          onChanged();
        } else {
          itemBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gItem item = 1;</code>
       */
      public protos.ItemServiceOuterClass.gItem.Builder getItemBuilder(
          int index) {
        return getItemFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Protos.gItem item = 1;</code>
       */
      public protos.ItemServiceOuterClass.gItemOrBuilder getItemOrBuilder(
          int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);  } else {
          return itemBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Protos.gItem item = 1;</code>
       */
      public java.util.List<? extends protos.ItemServiceOuterClass.gItemOrBuilder> 
           getItemOrBuilderList() {
        if (itemBuilder_ != null) {
          return itemBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(item_);
        }
      }
      /**
       * <code>repeated .Protos.gItem item = 1;</code>
       */
      public protos.ItemServiceOuterClass.gItem.Builder addItemBuilder() {
        return getItemFieldBuilder().addBuilder(
            protos.ItemServiceOuterClass.gItem.getDefaultInstance());
      }
      /**
       * <code>repeated .Protos.gItem item = 1;</code>
       */
      public protos.ItemServiceOuterClass.gItem.Builder addItemBuilder(
          int index) {
        return getItemFieldBuilder().addBuilder(
            index, protos.ItemServiceOuterClass.gItem.getDefaultInstance());
      }
      /**
       * <code>repeated .Protos.gItem item = 1;</code>
       */
      public java.util.List<protos.ItemServiceOuterClass.gItem.Builder> 
           getItemBuilderList() {
        return getItemFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protos.ItemServiceOuterClass.gItem, protos.ItemServiceOuterClass.gItem.Builder, protos.ItemServiceOuterClass.gItemOrBuilder> 
          getItemFieldBuilder() {
        if (itemBuilder_ == null) {
          itemBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protos.ItemServiceOuterClass.gItem, protos.ItemServiceOuterClass.gItem.Builder, protos.ItemServiceOuterClass.gItemOrBuilder>(
                  item_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          item_ = null;
        }
        return itemBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.gItemList)
    }

    // @@protoc_insertion_point(class_scope:Protos.gItemList)
    private static final protos.ItemServiceOuterClass.gItemList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.ItemServiceOuterClass.gItemList();
    }

    public static protos.ItemServiceOuterClass.gItemList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<gItemList>
        PARSER = new com.google.protobuf.AbstractParser<gItemList>() {
      @java.lang.Override
      public gItemList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new gItemList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<gItemList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<gItemList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.ItemServiceOuterClass.gItemList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_gItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_gItem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_gItemList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_gItemList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ItemService.proto\022\006Protos\"d\n\005gItem\022\n\n\002" +
      "Id\030\001 \001(\005\022\020\n\010itemName\030\002 \001(\t\022\016\n\006length\030\003 \001" +
      "(\001\022\r\n\005width\030\004 \001(\001\022\016\n\006height\030\005 \001(\001\022\016\n\006wei" +
      "ght\030\006 \001(\001\"(\n\tgItemList\022\033\n\004item\030\001 \003(\0132\r.P" +
      "rotos.gItem2\355\001\n\013ItemService\022,\n\014RegisterI" +
      "tem\022\r.Protos.gItem\032\r.Protos.gItem\022\'\n\007Get" +
      "Item\022\r.Protos.gItem\032\r.Protos.gItem\022/\n\013Ge" +
      "tAllItems\022\r.Protos.gItem\032\021.Protos.gItemL" +
      "ist\022*\n\nUpdateItem\022\r.Protos.gItem\032\r.Proto" +
      "s.gItem\022*\n\nRemoveItem\022\r.Protos.gItem\032\r.P" +
      "rotos.gItemB\021\n\006protos\252\002\006myGrpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Protos_gItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Protos_gItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_gItem_descriptor,
        new java.lang.String[] { "Id", "ItemName", "Length", "Width", "Height", "Weight", });
    internal_static_Protos_gItemList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Protos_gItemList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_gItemList_descriptor,
        new java.lang.String[] { "Item", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
