// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemLocation.proto

package protos;

public final class ItemLocationOuterClass {
  private ItemLocationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface gItemLocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.gItemLocation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Protos.gItem item = 1;</code>
     */
    boolean hasItem();
    /**
     * <code>.Protos.gItem item = 1;</code>
     */
    protos.ItemOuterClass.gItem getItem();
    /**
     * <code>.Protos.gItem item = 1;</code>
     */
    protos.ItemOuterClass.gItemOrBuilder getItemOrBuilder();

    /**
     * <code>.Protos.gLocation location = 2;</code>
     */
    boolean hasLocation();
    /**
     * <code>.Protos.gLocation location = 2;</code>
     */
    protos.LocationOuterClass.gLocation getLocation();
    /**
     * <code>.Protos.gLocation location = 2;</code>
     */
    protos.LocationOuterClass.gLocationOrBuilder getLocationOrBuilder();

    /**
     * <code>int32 id = 3;</code>
     */
    int getId();

    /**
     * <code>int32 amount = 4;</code>
     */
    int getAmount();
  }
  /**
   * Protobuf type {@code Protos.gItemLocation}
   */
  public  static final class gItemLocation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.gItemLocation)
      gItemLocationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use gItemLocation.newBuilder() to construct.
    private gItemLocation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private gItemLocation() {
      id_ = 0;
      amount_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private gItemLocation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              protos.ItemOuterClass.gItem.Builder subBuilder = null;
              if (item_ != null) {
                subBuilder = item_.toBuilder();
              }
              item_ = input.readMessage(protos.ItemOuterClass.gItem.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(item_);
                item_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              protos.LocationOuterClass.gLocation.Builder subBuilder = null;
              if (location_ != null) {
                subBuilder = location_.toBuilder();
              }
              location_ = input.readMessage(protos.LocationOuterClass.gLocation.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(location_);
                location_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              id_ = input.readInt32();
              break;
            }
            case 32: {

              amount_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.ItemLocationOuterClass.internal_static_Protos_gItemLocation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.ItemLocationOuterClass.internal_static_Protos_gItemLocation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.ItemLocationOuterClass.gItemLocation.class, protos.ItemLocationOuterClass.gItemLocation.Builder.class);
    }

    public static final int ITEM_FIELD_NUMBER = 1;
    private protos.ItemOuterClass.gItem item_;
    /**
     * <code>.Protos.gItem item = 1;</code>
     */
    public boolean hasItem() {
      return item_ != null;
    }
    /**
     * <code>.Protos.gItem item = 1;</code>
     */
    public protos.ItemOuterClass.gItem getItem() {
      return item_ == null ? protos.ItemOuterClass.gItem.getDefaultInstance() : item_;
    }
    /**
     * <code>.Protos.gItem item = 1;</code>
     */
    public protos.ItemOuterClass.gItemOrBuilder getItemOrBuilder() {
      return getItem();
    }

    public static final int LOCATION_FIELD_NUMBER = 2;
    private protos.LocationOuterClass.gLocation location_;
    /**
     * <code>.Protos.gLocation location = 2;</code>
     */
    public boolean hasLocation() {
      return location_ != null;
    }
    /**
     * <code>.Protos.gLocation location = 2;</code>
     */
    public protos.LocationOuterClass.gLocation getLocation() {
      return location_ == null ? protos.LocationOuterClass.gLocation.getDefaultInstance() : location_;
    }
    /**
     * <code>.Protos.gLocation location = 2;</code>
     */
    public protos.LocationOuterClass.gLocationOrBuilder getLocationOrBuilder() {
      return getLocation();
    }

    public static final int ID_FIELD_NUMBER = 3;
    private int id_;
    /**
     * <code>int32 id = 3;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int AMOUNT_FIELD_NUMBER = 4;
    private int amount_;
    /**
     * <code>int32 amount = 4;</code>
     */
    public int getAmount() {
      return amount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (item_ != null) {
        output.writeMessage(1, getItem());
      }
      if (location_ != null) {
        output.writeMessage(2, getLocation());
      }
      if (id_ != 0) {
        output.writeInt32(3, id_);
      }
      if (amount_ != 0) {
        output.writeInt32(4, amount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (item_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getItem());
      }
      if (location_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLocation());
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, id_);
      }
      if (amount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, amount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.ItemLocationOuterClass.gItemLocation)) {
        return super.equals(obj);
      }
      protos.ItemLocationOuterClass.gItemLocation other = (protos.ItemLocationOuterClass.gItemLocation) obj;

      boolean result = true;
      result = result && (hasItem() == other.hasItem());
      if (hasItem()) {
        result = result && getItem()
            .equals(other.getItem());
      }
      result = result && (hasLocation() == other.hasLocation());
      if (hasLocation()) {
        result = result && getLocation()
            .equals(other.getLocation());
      }
      result = result && (getId()
          == other.getId());
      result = result && (getAmount()
          == other.getAmount());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasItem()) {
        hash = (37 * hash) + ITEM_FIELD_NUMBER;
        hash = (53 * hash) + getItem().hashCode();
      }
      if (hasLocation()) {
        hash = (37 * hash) + LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getLocation().hashCode();
      }
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAmount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.ItemLocationOuterClass.gItemLocation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.ItemLocationOuterClass.gItemLocation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.ItemLocationOuterClass.gItemLocation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.ItemLocationOuterClass.gItemLocation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.ItemLocationOuterClass.gItemLocation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.ItemLocationOuterClass.gItemLocation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.ItemLocationOuterClass.gItemLocation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.ItemLocationOuterClass.gItemLocation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.ItemLocationOuterClass.gItemLocation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.ItemLocationOuterClass.gItemLocation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.ItemLocationOuterClass.gItemLocation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.ItemLocationOuterClass.gItemLocation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.ItemLocationOuterClass.gItemLocation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protos.gItemLocation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.gItemLocation)
        protos.ItemLocationOuterClass.gItemLocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.ItemLocationOuterClass.internal_static_Protos_gItemLocation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.ItemLocationOuterClass.internal_static_Protos_gItemLocation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.ItemLocationOuterClass.gItemLocation.class, protos.ItemLocationOuterClass.gItemLocation.Builder.class);
      }

      // Construct using protos.ItemLocationOuterClass.gItemLocation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (itemBuilder_ == null) {
          item_ = null;
        } else {
          item_ = null;
          itemBuilder_ = null;
        }
        if (locationBuilder_ == null) {
          location_ = null;
        } else {
          location_ = null;
          locationBuilder_ = null;
        }
        id_ = 0;

        amount_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.ItemLocationOuterClass.internal_static_Protos_gItemLocation_descriptor;
      }

      @java.lang.Override
      public protos.ItemLocationOuterClass.gItemLocation getDefaultInstanceForType() {
        return protos.ItemLocationOuterClass.gItemLocation.getDefaultInstance();
      }

      @java.lang.Override
      public protos.ItemLocationOuterClass.gItemLocation build() {
        protos.ItemLocationOuterClass.gItemLocation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.ItemLocationOuterClass.gItemLocation buildPartial() {
        protos.ItemLocationOuterClass.gItemLocation result = new protos.ItemLocationOuterClass.gItemLocation(this);
        if (itemBuilder_ == null) {
          result.item_ = item_;
        } else {
          result.item_ = itemBuilder_.build();
        }
        if (locationBuilder_ == null) {
          result.location_ = location_;
        } else {
          result.location_ = locationBuilder_.build();
        }
        result.id_ = id_;
        result.amount_ = amount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.ItemLocationOuterClass.gItemLocation) {
          return mergeFrom((protos.ItemLocationOuterClass.gItemLocation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.ItemLocationOuterClass.gItemLocation other) {
        if (other == protos.ItemLocationOuterClass.gItemLocation.getDefaultInstance()) return this;
        if (other.hasItem()) {
          mergeItem(other.getItem());
        }
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getAmount() != 0) {
          setAmount(other.getAmount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.ItemLocationOuterClass.gItemLocation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.ItemLocationOuterClass.gItemLocation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private protos.ItemOuterClass.gItem item_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          protos.ItemOuterClass.gItem, protos.ItemOuterClass.gItem.Builder, protos.ItemOuterClass.gItemOrBuilder> itemBuilder_;
      /**
       * <code>.Protos.gItem item = 1;</code>
       */
      public boolean hasItem() {
        return itemBuilder_ != null || item_ != null;
      }
      /**
       * <code>.Protos.gItem item = 1;</code>
       */
      public protos.ItemOuterClass.gItem getItem() {
        if (itemBuilder_ == null) {
          return item_ == null ? protos.ItemOuterClass.gItem.getDefaultInstance() : item_;
        } else {
          return itemBuilder_.getMessage();
        }
      }
      /**
       * <code>.Protos.gItem item = 1;</code>
       */
      public Builder setItem(protos.ItemOuterClass.gItem value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          item_ = value;
          onChanged();
        } else {
          itemBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Protos.gItem item = 1;</code>
       */
      public Builder setItem(
          protos.ItemOuterClass.gItem.Builder builderForValue) {
        if (itemBuilder_ == null) {
          item_ = builderForValue.build();
          onChanged();
        } else {
          itemBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Protos.gItem item = 1;</code>
       */
      public Builder mergeItem(protos.ItemOuterClass.gItem value) {
        if (itemBuilder_ == null) {
          if (item_ != null) {
            item_ =
              protos.ItemOuterClass.gItem.newBuilder(item_).mergeFrom(value).buildPartial();
          } else {
            item_ = value;
          }
          onChanged();
        } else {
          itemBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Protos.gItem item = 1;</code>
       */
      public Builder clearItem() {
        if (itemBuilder_ == null) {
          item_ = null;
          onChanged();
        } else {
          item_ = null;
          itemBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Protos.gItem item = 1;</code>
       */
      public protos.ItemOuterClass.gItem.Builder getItemBuilder() {
        
        onChanged();
        return getItemFieldBuilder().getBuilder();
      }
      /**
       * <code>.Protos.gItem item = 1;</code>
       */
      public protos.ItemOuterClass.gItemOrBuilder getItemOrBuilder() {
        if (itemBuilder_ != null) {
          return itemBuilder_.getMessageOrBuilder();
        } else {
          return item_ == null ?
              protos.ItemOuterClass.gItem.getDefaultInstance() : item_;
        }
      }
      /**
       * <code>.Protos.gItem item = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protos.ItemOuterClass.gItem, protos.ItemOuterClass.gItem.Builder, protos.ItemOuterClass.gItemOrBuilder> 
          getItemFieldBuilder() {
        if (itemBuilder_ == null) {
          itemBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protos.ItemOuterClass.gItem, protos.ItemOuterClass.gItem.Builder, protos.ItemOuterClass.gItemOrBuilder>(
                  getItem(),
                  getParentForChildren(),
                  isClean());
          item_ = null;
        }
        return itemBuilder_;
      }

      private protos.LocationOuterClass.gLocation location_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          protos.LocationOuterClass.gLocation, protos.LocationOuterClass.gLocation.Builder, protos.LocationOuterClass.gLocationOrBuilder> locationBuilder_;
      /**
       * <code>.Protos.gLocation location = 2;</code>
       */
      public boolean hasLocation() {
        return locationBuilder_ != null || location_ != null;
      }
      /**
       * <code>.Protos.gLocation location = 2;</code>
       */
      public protos.LocationOuterClass.gLocation getLocation() {
        if (locationBuilder_ == null) {
          return location_ == null ? protos.LocationOuterClass.gLocation.getDefaultInstance() : location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>.Protos.gLocation location = 2;</code>
       */
      public Builder setLocation(protos.LocationOuterClass.gLocation value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
          onChanged();
        } else {
          locationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Protos.gLocation location = 2;</code>
       */
      public Builder setLocation(
          protos.LocationOuterClass.gLocation.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
          onChanged();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Protos.gLocation location = 2;</code>
       */
      public Builder mergeLocation(protos.LocationOuterClass.gLocation value) {
        if (locationBuilder_ == null) {
          if (location_ != null) {
            location_ =
              protos.LocationOuterClass.gLocation.newBuilder(location_).mergeFrom(value).buildPartial();
          } else {
            location_ = value;
          }
          onChanged();
        } else {
          locationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Protos.gLocation location = 2;</code>
       */
      public Builder clearLocation() {
        if (locationBuilder_ == null) {
          location_ = null;
          onChanged();
        } else {
          location_ = null;
          locationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Protos.gLocation location = 2;</code>
       */
      public protos.LocationOuterClass.gLocation.Builder getLocationBuilder() {
        
        onChanged();
        return getLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>.Protos.gLocation location = 2;</code>
       */
      public protos.LocationOuterClass.gLocationOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_ == null ?
              protos.LocationOuterClass.gLocation.getDefaultInstance() : location_;
        }
      }
      /**
       * <code>.Protos.gLocation location = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protos.LocationOuterClass.gLocation, protos.LocationOuterClass.gLocation.Builder, protos.LocationOuterClass.gLocationOrBuilder> 
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protos.LocationOuterClass.gLocation, protos.LocationOuterClass.gLocation.Builder, protos.LocationOuterClass.gLocationOrBuilder>(
                  getLocation(),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }

      private int id_ ;
      /**
       * <code>int32 id = 3;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 3;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 3;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int amount_ ;
      /**
       * <code>int32 amount = 4;</code>
       */
      public int getAmount() {
        return amount_;
      }
      /**
       * <code>int32 amount = 4;</code>
       */
      public Builder setAmount(int value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 amount = 4;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.gItemLocation)
    }

    // @@protoc_insertion_point(class_scope:Protos.gItemLocation)
    private static final protos.ItemLocationOuterClass.gItemLocation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.ItemLocationOuterClass.gItemLocation();
    }

    public static protos.ItemLocationOuterClass.gItemLocation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<gItemLocation>
        PARSER = new com.google.protobuf.AbstractParser<gItemLocation>() {
      @java.lang.Override
      public gItemLocation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new gItemLocation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<gItemLocation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<gItemLocation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.ItemLocationOuterClass.gItemLocation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface gItemLocationListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.gItemLocationList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
     */
    java.util.List<protos.ItemLocationOuterClass.gItemLocation> 
        getItemLocationsList();
    /**
     * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
     */
    protos.ItemLocationOuterClass.gItemLocation getItemLocations(int index);
    /**
     * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
     */
    int getItemLocationsCount();
    /**
     * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
     */
    java.util.List<? extends protos.ItemLocationOuterClass.gItemLocationOrBuilder> 
        getItemLocationsOrBuilderList();
    /**
     * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
     */
    protos.ItemLocationOuterClass.gItemLocationOrBuilder getItemLocationsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Protos.gItemLocationList}
   */
  public  static final class gItemLocationList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.gItemLocationList)
      gItemLocationListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use gItemLocationList.newBuilder() to construct.
    private gItemLocationList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private gItemLocationList() {
      itemLocations_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private gItemLocationList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                itemLocations_ = new java.util.ArrayList<protos.ItemLocationOuterClass.gItemLocation>();
                mutable_bitField0_ |= 0x00000001;
              }
              itemLocations_.add(
                  input.readMessage(protos.ItemLocationOuterClass.gItemLocation.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          itemLocations_ = java.util.Collections.unmodifiableList(itemLocations_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.ItemLocationOuterClass.internal_static_Protos_gItemLocationList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.ItemLocationOuterClass.internal_static_Protos_gItemLocationList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.ItemLocationOuterClass.gItemLocationList.class, protos.ItemLocationOuterClass.gItemLocationList.Builder.class);
    }

    public static final int ITEMLOCATIONS_FIELD_NUMBER = 1;
    private java.util.List<protos.ItemLocationOuterClass.gItemLocation> itemLocations_;
    /**
     * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
     */
    public java.util.List<protos.ItemLocationOuterClass.gItemLocation> getItemLocationsList() {
      return itemLocations_;
    }
    /**
     * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
     */
    public java.util.List<? extends protos.ItemLocationOuterClass.gItemLocationOrBuilder> 
        getItemLocationsOrBuilderList() {
      return itemLocations_;
    }
    /**
     * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
     */
    public int getItemLocationsCount() {
      return itemLocations_.size();
    }
    /**
     * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
     */
    public protos.ItemLocationOuterClass.gItemLocation getItemLocations(int index) {
      return itemLocations_.get(index);
    }
    /**
     * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
     */
    public protos.ItemLocationOuterClass.gItemLocationOrBuilder getItemLocationsOrBuilder(
        int index) {
      return itemLocations_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < itemLocations_.size(); i++) {
        output.writeMessage(1, itemLocations_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < itemLocations_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, itemLocations_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.ItemLocationOuterClass.gItemLocationList)) {
        return super.equals(obj);
      }
      protos.ItemLocationOuterClass.gItemLocationList other = (protos.ItemLocationOuterClass.gItemLocationList) obj;

      boolean result = true;
      result = result && getItemLocationsList()
          .equals(other.getItemLocationsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemLocationsCount() > 0) {
        hash = (37 * hash) + ITEMLOCATIONS_FIELD_NUMBER;
        hash = (53 * hash) + getItemLocationsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.ItemLocationOuterClass.gItemLocationList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.ItemLocationOuterClass.gItemLocationList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.ItemLocationOuterClass.gItemLocationList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.ItemLocationOuterClass.gItemLocationList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.ItemLocationOuterClass.gItemLocationList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.ItemLocationOuterClass.gItemLocationList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.ItemLocationOuterClass.gItemLocationList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.ItemLocationOuterClass.gItemLocationList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.ItemLocationOuterClass.gItemLocationList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.ItemLocationOuterClass.gItemLocationList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.ItemLocationOuterClass.gItemLocationList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.ItemLocationOuterClass.gItemLocationList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.ItemLocationOuterClass.gItemLocationList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protos.gItemLocationList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.gItemLocationList)
        protos.ItemLocationOuterClass.gItemLocationListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.ItemLocationOuterClass.internal_static_Protos_gItemLocationList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.ItemLocationOuterClass.internal_static_Protos_gItemLocationList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.ItemLocationOuterClass.gItemLocationList.class, protos.ItemLocationOuterClass.gItemLocationList.Builder.class);
      }

      // Construct using protos.ItemLocationOuterClass.gItemLocationList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemLocationsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (itemLocationsBuilder_ == null) {
          itemLocations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemLocationsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.ItemLocationOuterClass.internal_static_Protos_gItemLocationList_descriptor;
      }

      @java.lang.Override
      public protos.ItemLocationOuterClass.gItemLocationList getDefaultInstanceForType() {
        return protos.ItemLocationOuterClass.gItemLocationList.getDefaultInstance();
      }

      @java.lang.Override
      public protos.ItemLocationOuterClass.gItemLocationList build() {
        protos.ItemLocationOuterClass.gItemLocationList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.ItemLocationOuterClass.gItemLocationList buildPartial() {
        protos.ItemLocationOuterClass.gItemLocationList result = new protos.ItemLocationOuterClass.gItemLocationList(this);
        int from_bitField0_ = bitField0_;
        if (itemLocationsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            itemLocations_ = java.util.Collections.unmodifiableList(itemLocations_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.itemLocations_ = itemLocations_;
        } else {
          result.itemLocations_ = itemLocationsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.ItemLocationOuterClass.gItemLocationList) {
          return mergeFrom((protos.ItemLocationOuterClass.gItemLocationList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.ItemLocationOuterClass.gItemLocationList other) {
        if (other == protos.ItemLocationOuterClass.gItemLocationList.getDefaultInstance()) return this;
        if (itemLocationsBuilder_ == null) {
          if (!other.itemLocations_.isEmpty()) {
            if (itemLocations_.isEmpty()) {
              itemLocations_ = other.itemLocations_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemLocationsIsMutable();
              itemLocations_.addAll(other.itemLocations_);
            }
            onChanged();
          }
        } else {
          if (!other.itemLocations_.isEmpty()) {
            if (itemLocationsBuilder_.isEmpty()) {
              itemLocationsBuilder_.dispose();
              itemLocationsBuilder_ = null;
              itemLocations_ = other.itemLocations_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemLocationsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemLocationsFieldBuilder() : null;
            } else {
              itemLocationsBuilder_.addAllMessages(other.itemLocations_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.ItemLocationOuterClass.gItemLocationList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.ItemLocationOuterClass.gItemLocationList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<protos.ItemLocationOuterClass.gItemLocation> itemLocations_ =
        java.util.Collections.emptyList();
      private void ensureItemLocationsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          itemLocations_ = new java.util.ArrayList<protos.ItemLocationOuterClass.gItemLocation>(itemLocations_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protos.ItemLocationOuterClass.gItemLocation, protos.ItemLocationOuterClass.gItemLocation.Builder, protos.ItemLocationOuterClass.gItemLocationOrBuilder> itemLocationsBuilder_;

      /**
       * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
       */
      public java.util.List<protos.ItemLocationOuterClass.gItemLocation> getItemLocationsList() {
        if (itemLocationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(itemLocations_);
        } else {
          return itemLocationsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
       */
      public int getItemLocationsCount() {
        if (itemLocationsBuilder_ == null) {
          return itemLocations_.size();
        } else {
          return itemLocationsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
       */
      public protos.ItemLocationOuterClass.gItemLocation getItemLocations(int index) {
        if (itemLocationsBuilder_ == null) {
          return itemLocations_.get(index);
        } else {
          return itemLocationsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
       */
      public Builder setItemLocations(
          int index, protos.ItemLocationOuterClass.gItemLocation value) {
        if (itemLocationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemLocationsIsMutable();
          itemLocations_.set(index, value);
          onChanged();
        } else {
          itemLocationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
       */
      public Builder setItemLocations(
          int index, protos.ItemLocationOuterClass.gItemLocation.Builder builderForValue) {
        if (itemLocationsBuilder_ == null) {
          ensureItemLocationsIsMutable();
          itemLocations_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemLocationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
       */
      public Builder addItemLocations(protos.ItemLocationOuterClass.gItemLocation value) {
        if (itemLocationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemLocationsIsMutable();
          itemLocations_.add(value);
          onChanged();
        } else {
          itemLocationsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
       */
      public Builder addItemLocations(
          int index, protos.ItemLocationOuterClass.gItemLocation value) {
        if (itemLocationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemLocationsIsMutable();
          itemLocations_.add(index, value);
          onChanged();
        } else {
          itemLocationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
       */
      public Builder addItemLocations(
          protos.ItemLocationOuterClass.gItemLocation.Builder builderForValue) {
        if (itemLocationsBuilder_ == null) {
          ensureItemLocationsIsMutable();
          itemLocations_.add(builderForValue.build());
          onChanged();
        } else {
          itemLocationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
       */
      public Builder addItemLocations(
          int index, protos.ItemLocationOuterClass.gItemLocation.Builder builderForValue) {
        if (itemLocationsBuilder_ == null) {
          ensureItemLocationsIsMutable();
          itemLocations_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemLocationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
       */
      public Builder addAllItemLocations(
          java.lang.Iterable<? extends protos.ItemLocationOuterClass.gItemLocation> values) {
        if (itemLocationsBuilder_ == null) {
          ensureItemLocationsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, itemLocations_);
          onChanged();
        } else {
          itemLocationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
       */
      public Builder clearItemLocations() {
        if (itemLocationsBuilder_ == null) {
          itemLocations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemLocationsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
       */
      public Builder removeItemLocations(int index) {
        if (itemLocationsBuilder_ == null) {
          ensureItemLocationsIsMutable();
          itemLocations_.remove(index);
          onChanged();
        } else {
          itemLocationsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
       */
      public protos.ItemLocationOuterClass.gItemLocation.Builder getItemLocationsBuilder(
          int index) {
        return getItemLocationsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
       */
      public protos.ItemLocationOuterClass.gItemLocationOrBuilder getItemLocationsOrBuilder(
          int index) {
        if (itemLocationsBuilder_ == null) {
          return itemLocations_.get(index);  } else {
          return itemLocationsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
       */
      public java.util.List<? extends protos.ItemLocationOuterClass.gItemLocationOrBuilder> 
           getItemLocationsOrBuilderList() {
        if (itemLocationsBuilder_ != null) {
          return itemLocationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(itemLocations_);
        }
      }
      /**
       * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
       */
      public protos.ItemLocationOuterClass.gItemLocation.Builder addItemLocationsBuilder() {
        return getItemLocationsFieldBuilder().addBuilder(
            protos.ItemLocationOuterClass.gItemLocation.getDefaultInstance());
      }
      /**
       * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
       */
      public protos.ItemLocationOuterClass.gItemLocation.Builder addItemLocationsBuilder(
          int index) {
        return getItemLocationsFieldBuilder().addBuilder(
            index, protos.ItemLocationOuterClass.gItemLocation.getDefaultInstance());
      }
      /**
       * <code>repeated .Protos.gItemLocation itemLocations = 1;</code>
       */
      public java.util.List<protos.ItemLocationOuterClass.gItemLocation.Builder> 
           getItemLocationsBuilderList() {
        return getItemLocationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protos.ItemLocationOuterClass.gItemLocation, protos.ItemLocationOuterClass.gItemLocation.Builder, protos.ItemLocationOuterClass.gItemLocationOrBuilder> 
          getItemLocationsFieldBuilder() {
        if (itemLocationsBuilder_ == null) {
          itemLocationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protos.ItemLocationOuterClass.gItemLocation, protos.ItemLocationOuterClass.gItemLocation.Builder, protos.ItemLocationOuterClass.gItemLocationOrBuilder>(
                  itemLocations_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          itemLocations_ = null;
        }
        return itemLocationsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.gItemLocationList)
    }

    // @@protoc_insertion_point(class_scope:Protos.gItemLocationList)
    private static final protos.ItemLocationOuterClass.gItemLocationList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.ItemLocationOuterClass.gItemLocationList();
    }

    public static protos.ItemLocationOuterClass.gItemLocationList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<gItemLocationList>
        PARSER = new com.google.protobuf.AbstractParser<gItemLocationList>() {
      @java.lang.Override
      public gItemLocationList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new gItemLocationList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<gItemLocationList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<gItemLocationList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.ItemLocationOuterClass.gItemLocationList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_gItemLocation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_gItemLocation_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_gItemLocationList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_gItemLocationList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ItemLocation.proto\022\006Protos\032\nItem.proto" +
      "\032\016Location.proto\"m\n\rgItemLocation\022\033\n\004ite" +
      "m\030\001 \001(\0132\r.Protos.gItem\022#\n\010location\030\002 \001(\013" +
      "2\021.Protos.gLocation\022\n\n\002id\030\003 \001(\005\022\016\n\006amoun" +
      "t\030\004 \001(\005\"A\n\021gItemLocationList\022,\n\ritemLoca" +
      "tions\030\001 \003(\0132\025.Protos.gItemLocation2\353\003\n\014I" +
      "temLocation\022D\n\024RegisterItemLocation\022\025.Pr" +
      "otos.gItemLocation\032\025.Protos.gItemLocatio" +
      "n\022?\n\017GetItemLocation\022\025.Protos.gItemLocat" +
      "ion\032\025.Protos.gItemLocation\022F\n\022GetAllItem" +
      "Location\022\025.Protos.gItemLocation\032\031.Protos" +
      ".gItemLocationList\022B\n\022UpdateItemLocation" +
      "\022\025.Protos.gItemLocation\032\025.Protos.gItemLo" +
      "cation\022B\n\022RemoveItemLocation\022\025.Protos.gI" +
      "temLocation\032\025.Protos.gItemLocation\022?\n\013Ge" +
      "tByItemId\022\025.Protos.gItemLocation\032\031.Proto" +
      "s.gItemLocationList\022C\n\017GetByLocationId\022\025" +
      ".Protos.gItemLocation\032\031.Protos.gItemLoca" +
      "tionListB\021\n\006protos\252\002\006myGrpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protos.ItemOuterClass.getDescriptor(),
          protos.LocationOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Protos_gItemLocation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Protos_gItemLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_gItemLocation_descriptor,
        new java.lang.String[] { "Item", "Location", "Id", "Amount", });
    internal_static_Protos_gItemLocationList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Protos_gItemLocationList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_gItemLocationList_descriptor,
        new java.lang.String[] { "ItemLocations", });
    protos.ItemOuterClass.getDescriptor();
    protos.LocationOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
